#if DEBUG
import BharatStockCore
import SwiftUI
import WidgetKit

/// §7's appearance matrix: all four sizes × Light, Dark, Increased Contrast, Reduced Transparency,
/// and Liquid Glass on/off.
///
/// Generated by iterating over the two axes rather than written out by hand, so adding a size or a
/// variant is a one-line change and no combination can be quietly forgotten.
///
/// Two notes on what a preview can and cannot reach:
/// - Reduce Transparency is read-only in `EnvironmentValues`, so it is driven through
///   `AppearanceOverrides`. "Liquid Glass off" is the same axis from the user's point of view: it
///   is the case where the system paints an opaque material instead of letting the glass through.
/// - `colorSchemeContrast` is genuinely read-only with no override hook. The Increased Contrast
///   column is therefore shown in its normal-contrast form here, and is correct by construction:
///   every colour in the widget is a semantic system colour, which the system re-resolves for
///   increased contrast without this code participating. Verify it once with the System Settings
///   toggle; there is nothing for a preview to assert.
enum PreviewMatrix {
    struct Variant: Identifiable {
        let name: String
        let colorScheme: ColorScheme
        let overrides: AppearanceOverrides

        var id: String { name }
    }

    static let variants: [Variant] = [
        Variant(name: "Light", colorScheme: .light, overrides: .none),
        Variant(name: "Dark", colorScheme: .dark, overrides: .none),
        Variant(
            name: "Light · Reduced Transparency",
            colorScheme: .light,
            overrides: AppearanceOverrides(reduceTransparency: true)
        ),
        Variant(
            name: "Dark · Reduced Transparency",
            colorScheme: .dark,
            overrides: AppearanceOverrides(reduceTransparency: true)
        ),
        Variant(
            name: "Dark · Reduced Motion",
            colorScheme: .dark,
            overrides: AppearanceOverrides(reduceMotion: true)
        ),
    ]

    static let families: [WidgetFamily] = WidgetSizes.supported
}

/// The full size × appearance grid on healthy data.
struct AppearanceMatrixPreviews: PreviewProvider {
    static var previews: some View {
        ForEach(PreviewMatrix.families, id: \.self) { family in
            ForEach(PreviewMatrix.variants) { variant in
                QuoteWidgetView(entry: QuoteEntry(date: .now, cache: SampleData.cache, display: .default))
                    .environment(\.appearanceOverrides, variant.overrides)
                    .environment(\.colorScheme, variant.colorScheme)
                    .previewContext(WidgetPreviewContext(family: family))
                    .previewDisplayName("\(WidgetSizes.describe(family)) · \(variant.name)")
            }
        }
    }

}

/// Every degraded state at Medium and Large. §10 requires each of these to be legible, so each
/// one gets a preview rather than being taken on trust.
struct DegradedStatePreviews: PreviewProvider {
    static let statuses: [CacheStatus] = [
        .ok, .partial, .stale, .budgetExhausted, .configError, .authError,
    ]

    static var previews: some View {
        ForEach([WidgetFamily.systemMedium, .systemLarge], id: \.self) { family in
            ForEach(statuses, id: \.rawValue) { status in
                QuoteWidgetView(
                    entry: QuoteEntry(date: .now, cache: SampleData.degraded(status), display: .default)
                )
                .previewContext(WidgetPreviewContext(family: family))
                .previewDisplayName("\(WidgetSizes.describe(family)) · \(status.rawValue)")
            }
        }
    }
}

/// The states a fresh install and a Dynamic Type user see.
struct EdgeCasePreviews: PreviewProvider {
    static var previews: some View {
        ForEach(PreviewMatrix.families, id: \.self) { family in
            QuoteWidgetView(entry: QuoteEntry(date: .now, cache: SampleData.empty, display: .default))
                .previewContext(WidgetPreviewContext(family: family))
                .previewDisplayName("\(WidgetSizes.describe(family)) · empty")
        }

        // §7: at the largest sizes the change-% column is dropped rather than truncating the name.
        ForEach([DynamicTypeSize.large, .xxxLarge, .accessibility3], id: \.self) { size in
            QuoteWidgetView(entry: QuoteEntry(date: .now, cache: SampleData.cache, display: .default))
                .environment(\.dynamicTypeSize, size)
                .previewContext(WidgetPreviewContext(family: .systemLarge))
                .previewDisplayName("Large · Dynamic Type \(size)")
        }

        // Fewer instruments than the size allows: render what exists, pad nothing.
        QuoteWidgetView(
            entry: QuoteEntry(
                date: .now,
                cache: QuoteCache(
                    generatedAtUTC: .now,
                    lastSuccessfulFetchUTC: .now,
                    sourceTradingDate: SampleData.tradingDate,
                    budget: .init(spent: 2, limit: 50),
                    status: .ok,
                    rows: Array(SampleData.rows.prefix(2))
                ),
                display: .default
            )
        )
        .previewContext(WidgetPreviewContext(family: .systemLarge))
        .previewDisplayName("Large · only 2 instruments")
    }
}
#endif
